name: teck_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  local_auth: ^2.1.6
  local_auth_darwin: ^1.4.2
  shared_preferences: ^2.5.1
  google_sign_in: ^6.1.6
  firebase_core: ^3.12.1
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.1.0
  share_plus: ^10.1.4
  printing: ^5.14.2
  pdf: ^3.11.3
  fl_chart: ^0.70.2
  intl: ^0.19.0
  skeletonizer: ^1.4.3
  get: ^4.6.6
  flutter_svg: ^2.0.17
  sqflite: ^2.4.1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/teckapp_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/teckapp_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/